
from data_manager import get_data
def classify_actions_rse_ODD(data):
    criteria = {"Fin de la pauvreté":[],
                "Faim":[],
                "Bonne santé et bien-être":[],
                "Éducation de qualité":[],
                "Égalité en les sexes":[],
                "Eau propre et assainissement":[],
                "Énergie propre et d'une coût durable":[],
                "Travail décent et crossaince économique":[],
                "Industrie, inovation et infrastructure":[],
                "Inégalités réduites":[],
                "Villes et communautés durables":[],
                "Consommmation et production responsables":[],
                "Mesures relatives à la lutte contre les changements climatiques":[],
                "Vie aquatique":[],
                "Vie terrestre":[],
                "Paix, justice et institutions efficaces":[],
                "Partenariats pour la réalisation des objectifs":[],
                "ODD Autres": []
    }

    keywords ={"Fin de la pauvreté":["pauvreté","exclusion sociale","aide financière","microfinance","soutien économique","emploi","aide d'urgence","développement économique local","sécurité financière","revenu de base","lutte contre la précarité","insertion professionnelle","programmes sociaux","aide aux sans-abri","solidarité","équité économique","initiatives de charité","subventions pour les pauvres"],
                "Faim":["faim","sécurité alimentaire","nutrition","agriculture durable","accès à l'alimentation","malnutrition","programmes alimentaires","cultures bio","soutien aux agriculteurs","technologies agricoles","chaînes d'approvisionnement","aide alimentaire","bancs alimentaires","alimentation saine","éducation nutritionnelle","lutte contre la sous-nutrition","résilience agricole","permaculture"],
                "Bonne santé et bien-être":["santé","bien-être","soins médicaux","prévention","maladies","santé mantale","vaccination","systèmes de santé","accès aux soins","santé reproductive","éducation sanitaire","sport et santé","lutte contre les épidémies","recherche médicale","sécurité sanitaire","hygiène","soins primaires","bien-être au travail","soutien psychologique"],
                "Éducation de qualité":["éducation","apprentissage","scolarisation","éducation pour tous","alphabétisation","compétences numériques","écoles","enseignement supérieur","formation professionnelle","éducation inclusive","bourses d'études","technologies éducatives","qualité de l'enseignement","développement des compétences","éducation des filles","éducation permanente","innovation pédagogique","accès à l'éducation"],
                "Égalité en les sexes":["égalité des genres","femmes","droits des femmes","autonomisation des femmes","violence de genre","parité","discrimination","leadership féminin","équité salariale","éducation des filles","santé des femmes","participation politique","accès aux ressources","lutte contre le harcèlement","émancipation","mentorat féminin","réseaux de femmes","protection des droits"],
                "Eau propre et assainissement":["eau potable","assainissement","gestion de l'eau","infrastructures hydrauliques","traitement de l'eau","accès à l'eau","qualité de l'eau","économie d'eau","sanitaires","hygiène","technologies de l'eau","conservation de l'eau","eaux usées","risques hydriques","irrigation","eau et climat","protection des sources","éducation à l'eau"],
                "Énergie propre et d'une coût durable":["énergie renouvelable","accès à l'énergie","énergie durable","énergie solaire","énergie éolienne","efficacité énergétique","technologies propres","réduction des émissions","bioénergie","énergie hydroélectrique","réseaux électriques","transition énergétique","subventions énergétiques","énergie pour tous","isolation thermique","énergies alternatives","consommation d'énergie","énergie verte"],
                "Travail décent et crossaince économique":["emploi","croissance économique","travail décent","droits du travail","création d'emploi","entrepreneuriat","économie formelle","conditions de travail","sécurité de l'emploi","développement économique","innovation économique","productivité","inclusion économique","salaires équitables","lutte contre le chômage","formation professionnelle","microentreprises","économie locale"],
                "Industrie, inovation et infrastructure":["infrastructure",
    "innovation",
    "industrie durable",
    "recherche et développement",
    "technologies",
    "transport durable",
    "urbanisation",
    "construction écologique",
    "parcs industriels",
    "efficacité industrielle",
    "investissement en infrastructure",
    "réseaux de communication",
    "qualité industrielle",
    "sécurité des infrastructures",
    "modernisation industrielle",
    "partenariats technologiques",
    "développement scientifique",
    "infrastructure inclusive"],
                "Inégalités réduites":["inégalités",
    "équité",
    "inclusion sociale",
    "discrimination",
    "droits de l'homme",
    "accès équitable",
    "diversité",
    "intégration sociale",
    "justice sociale",
    "égalité d'accès",
    "réduction des disparités",
    "politiques inclusives",
    "égalité des chances",
    "soutien aux minorités",
    "lutte contre la pauvreté",
    "mobilité sociale",
    "égalité économique",
    "disparités régionales"],
                "Villes et communautés durables":["urbanisme",
    "développement urbain",
    "villes durables",
    "communautés inclusives",
    "logement abordable",
    "transport urbain",
    "gestion des déchets",
    "espaces publics",
    "rénovation urbaine",
    "planification urbaine",
    "durabilité urbaine",
    "qualité de vie urbaine",
    "sécurité urbaine",
    "résilience climatique",
    "infrastructures vertes",
    "mobilité durable",
    "participation citoyenne",
    "gouvernance locale"],
                "Consommmation et production responsables":["consommation durable",
    "production durable",
    "gestion des ressources",
    "recyclage",
    "éco-conception",
    "réduction des déchets",
    "économie circulaire",
    "consommation responsable",
    "chaînes d'approvisionnement vertes",
    "empreinte écologique",
    "produits écologiques",
    "éthique de production",
    "efficacité des ressources",
    "déchets industriels",
    "marketing durable",
    "emballages durables",
    "gaspillage alimentaire",
    "responsabilité des producteurs"],
                "Mesures relatives à la lutte contre les changements climatiques":["changement climatique",
    "mitigation",
    "adaptation climatique",
    "réduction des émissions",
    "carboneutralité",
    "politiques climatiques",
    "sensibilisation au climat",
    "initiatives climatiques",
    "risques climatiques",
    "technologies vertes",
    "énergies renouvelables",
    "résilience climatique",
    "science du climat",
    "accords climatiques",
    "actions pour le climat",
    "financement climatique",
    "éducation au climat",
    "coopération climatique"],
                "Vie aquatique":["océans",
    "mers",
    "ressources marines",
    "pêche durable",
    "biodiversité marine",
    "écosystèmes marins",
    "pollution marine",
    "conservation marine",
    "aquaculture durable",
    "acidification des océans",
    "habitats marins",
    "protection des océans",
    "gestion des pêcheries",
    "zones marines protégées",
    "science marine",
    "économie bleue",
    "éducation marine",
    "coraux"],
                "Vie terrestre":["terres",
    "biodiversité",
    "écosystèmes terrestres",
    "conservation",
    "reforestation",
    "désertification",
    "terres agricoles",
    "faune et flore",
    "habitats naturels",
    "gestion durable des forêts",
    "espèces menacées",
    "sols",
    "parcs naturels",
    "restauration écologique",
    "gestion des terres",
    "utilisation des terres",
    "déforestation",
    "biodiversité terrestre"],
                "Paix, justice et institutions efficaces":["paix",
    "justice",
    "institutions efficaces",
    "droits de l'homme",
    "gouvernance",
    "corruption",
    "transparence",
    "état de droit",
    "sécurité",
    "institutions inclusives",
    "accès à la justice",
    "lutte contre la corruption",
    "droits civiques",
    "participation politique",
    "stabilité sociale",
    "prévention des conflits",
    "législation",
    "responsabilité"],
                "Partenariats pour la réalisation des objectifs":["partenariats","coopération internationale","développement durable","aide au développement","financement durable","collaboration multilatérale","technologies partagées","échange de connaissances","objectifs mondiaux","solidarité internationale","intégration économique","coopération technique","partenariats public-privé","alignement des politiques","capacité institutionnelle","mobilisation des ressources","engagement mondial","transfert de technologie"]
    }

    data, _ = get_data()

    for record in data:
        action_rse = record.get("action_rse", "").lower()
        company_info = {
            "name": record.get("nom_courant_denomination", "N/A"),
            "action_rse": action_rse,
            "activity": record.get("libelle_section_naf", "N/A"),
            "city": record.get("commune", "N/A")
        }
        found = False
        for criterion, key_phrases in keywords.items():
            if any(key_phrase in action_rse for key_phrase in key_phrases):
                criteria[criterion].append(company_info)
                found = True
                break
        if not found:
            criteria["ODD Autres"].append(company_info)

    return criteria
def display_results(criteria):

    for criterion, actions in criteria.items():
        print(f"{criterion}:")
        for action in actions:
            print(f"- {action['name']} ({action['city']}): {action['action_rse']}")

ODD_RSE = classify_actions_rse_ODD(get_data())
display_results(ODD_RSE)

